name: spatial-ml-env
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.10

  # Jupyter environment
  - jupyterlab
  - notebook
  - ipywidgets # For interactive notebooks
  - ipyleaflet # For interactive maps

  # Core data science and numerical
  - numpy
  - pandas
  - scikit-learn
  - scipy

  # Geospatial stack
  - geopandas
  - shapely
  - pyproj
  - fiona
  - rasterio
  - contextily
  - geodatasets # For loading sample data

  # Network Analysis
  - osmnx
  - networkx

  # Spatial Statistics (PySAL family)
  - esda
  - libpysal
  - pointpats
  
  # Geostatistics
  - pykrige

  # Optimization
  - pulp

  # Plotting
  - matplotlib
  - seaborn
  
  # Utility
  - requests # For downloading data
  - pip
  - pip:
    - faiss-cpu # For accelerated similarity search

